#!/usr/bin/env bash
# Builds OpenUSD for lucabRTrender into ~/tools/usd-<version>-mx.
#
# Why a script and not FetchContent: OpenUSD takes tens of minutes and brings
# its own oneTBB, OpenSubdiv and friends. Building it once per machine, next to
# ~/tools/slang, keeps the engine's configure step in seconds. The engine then
# links the oneTBB this build installs, so there is one TBB in the process.
#
# Why no Python: OpenUSD 26.08 does not yet support the Python 3.14 that
# Homebrew ships, and the engine needs none of it -- the PLY -> USD converter is
# `lrt convert`, in C++. usdview is therefore not built; `lrt view` is the viewer.
#
# With MaterialX (1.39.5, whose Slang generator the engine's materials are
# generated by) and OpenVDB with NanoVDB (volumes reach the GPU as NanoVDB
# grids). MATERIALX_SLANG_RHI_SOURCE_DIR stays unset: MaterialX's own Slang
# renderer would bring a second slang-rhi into the process.
#
# The prefix carries "-mx" so the previous build stays usable until the engine
# is green against this one.
#
# Usage: scripts/build-usd.sh [version]   (default v26.08)
set -euo pipefail

VERSION="${1:-v26.08}"
PREFIX="${LRT_USD_ROOT:-$HOME/tools/usd-${VERSION#v}-mx}"
SRC="${LRT_USD_SRC:-$HOME/tools/src/OpenUSD-${VERSION#v}}"
JOBS="${JOBS:-$(getconf _NPROCESSORS_ONLN)}"

if [[ ! -d "$SRC/.git" ]]; then
    mkdir -p "$(dirname "$SRC")"
    git clone --depth 1 --branch "$VERSION" \
        https://github.com/PixarAnimationStudios/OpenUSD.git "$SRC"
fi

# CMake 4 refuses projects declaring compatibility with CMake < 3.5, which
# c-blosc (an OpenVDB dependency) still does.
export CMAKE_POLICY_VERSION_MINIMUM=3.5

# Homebrew's libraries must not leak into the build; the flag exists only in
# build_usd.py's macOS options.
PLATFORM_ARGS=()
if [[ "$(uname)" == "Darwin" ]]; then
    PLATFORM_ARGS+=(--ignore-homebrew)
fi

PYTHON="$(command -v python3)"
"$PYTHON" "$SRC/build_scripts/build_usd.py" \
    --build-variant release \
    --no-python \
    --no-docs \
    --no-tests \
    --no-tutorials \
    --materialx \
    --no-embree \
    --no-ptex \
    --openvdb \
    --build-args "OpenVDB,-DOPENVDB_BUILD_NANOVDB=ON -DNANOVDB_USE_OPENVDB=ON" \
    --no-openimageio \
    --no-opencolorio \
    --onetbb \
    --usd-imaging \
    "${PLATFORM_ARGS[@]}" \
    --tools \
    --examples \
    -j "$JOBS" \
    "$PREFIX"

# GCC 13 rejects the injected-class-name written with its template arguments
# in a constructor of the bool specialisation (retainedDataSource.h:235,
# `HdRetainedTypedSampledDataSource<bool>(const bool&)`); clang accepts it.
# Only translation units that include the header meet it, which the light
# linking's retained data sources do. Patched in place so the prefix is the
# same one the Mac and the Linux machine build against.
HDR="$PREFIX/include/pxr/imaging/hd/retainedDataSource.h"
if grep -q "HdRetainedTypedSampledDataSource<bool>(const bool& value)" "$HDR"; then
    sed -i.orig "s/HdRetainedTypedSampledDataSource<bool>(const bool& value)/HdRetainedTypedSampledDataSource(const bool\& value)/" "$HDR"
    echo "patched ${HDR} for GCC 13"
fi

echo "OpenUSD ${VERSION} installed at ${PREFIX}"
echo "Configure lucabRTrender with -DLRT_USD_ROOT=${PREFIX} (the presets default to it)."
