// Copyright (c) 2026 lucabRTrender contributors.
//
// What GPU tests share: a device made once per process, a shader library, and
// helpers that run a checking kernel and read back only its counters.
//
// No CPU oracle anywhere: inputs are generated by kernels, results are checked
// by kernels, and what crosses back to the CPU is a handful of numbers.
#pragma once

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <memory>
#include <string>

#include "lrt/gpu/Buffer.h"
#include "lrt/gpu/CommandBatch.h"
#include "lrt/gpu/ComputeKernel.h"
#include "lrt/gpu/Device.h"
#include "lrt/gpu/ShaderLibrary.h"

namespace lrt::test {

struct Gpu {
    std::shared_ptr<gpu::Device>        device;
    std::unique_ptr<gpu::ShaderLibrary> library;
};

/// The process's test device, or null (the test SKIPs).
inline Gpu* gpuOrNull() {
    static std::unique_ptr<Gpu> kGpu = [] () -> std::unique_ptr<Gpu> {
        auto device = gpu::Device::create();
        if (!device) {
            return nullptr;
        }
        auto made = std::make_unique<Gpu>();
        made->device = *device;
        made->library = std::make_unique<gpu::ShaderLibrary>(made->device);
        return made;
    }();
    return kGpu.get();
}

#define LRT_REQUIRE_GPU(name)                         \
    ::lrt::test::Gpu* name = ::lrt::test::gpuOrNull(); \
    if (name == nullptr) {                             \
        SKIP("no GPU device");                         \
    }

inline gpu::Buffer uintBuffer(gpu::Device& device, uint64_t count, const char* label) {
    gpu::BufferDesc desc;
    desc.bytes = std::max<uint64_t>(count, 1) * sizeof(uint32_t);
    desc.elementBytes = sizeof(uint32_t);
    desc.label = label;
    auto made = gpu::Buffer::create(device, desc);
    REQUIRE(made);
    return *made;
}

/// The kernel in `module` whose entry point is named after the module, in
/// camelCase ("lrt/test/sort_stats" -> "sortStats"). `main` is not usable: Metal
/// reserves it.
inline std::string entryFor(const std::string& module) {
    std::string base = module.substr(module.rfind('/') + 1);
    std::string out;
    bool upper = false;
    for (char ch : base) {
        if (ch == '_') {
            upper = true;
            continue;
        }
        out += upper ? static_cast<char>(std::toupper(static_cast<unsigned char>(ch))) : ch;
        upper = false;
    }
    return out;
}

inline gpu::ComputeKernel kernel(Gpu& gpu, const std::string& module) {
    auto made = gpu::ComputeKernel::create(*gpu.library, module, entryFor(module));
    if (!made) {
        FAIL(made.error().toString());
    }
    return std::move(*made);
}

/// Folds 8-wide stats rows on the GPU and reads back the single row.
inline std::array<uint32_t, 8> reduceStats(Gpu& gpu, const gpu::Buffer& stats, uint32_t rows) {
    static gpu::ComputeKernel kReduce = kernel(gpu, "lrt/test/stats_reduce");
    gpu::Buffer result = uintBuffer(*gpu.device, 8, "stats.result");
    gpu::CommandBatch batch(*gpu.device);
    kReduce.dispatch(batch, {1, 1, 1}, [&](rhi::ShaderCursor cursor) {
        cursor["stats"].setBinding(stats.rhi());
        cursor["result"].setBinding(result.rhi());
        cursor["params"]["chunkCount"].setData(rows);
    });
    REQUIRE(batch.submit(true));
    std::array<uint32_t, 8> row{};
    REQUIRE(result.read(*gpu.device, 0, sizeof(row), row.data()));
    return row;
}

}   // namespace lrt::test
