// Copyright (c) 2026 lucabRTrender contributors.
//
// What GPU tests share: a device made once per process, a shader library, and
// helpers that run a checking kernel and read back only its counters.
//
// No CPU oracle anywhere: inputs are generated by kernels, results are checked
// by kernels, and what crosses back to the CPU is a handful of numbers.
#pragma once

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <array>
#include <cctype>
#include <cstdint>
#include <vector>
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <memory>
#include <string>

#include "lrt/gpu/Buffer.h"
#include "lrt/gpu/CommandBatch.h"
#include "lrt/gpu/ComputeKernel.h"
#include "lrt/gpu/Device.h"
#include "lrt/gpu/ShaderLibrary.h"

namespace lrt::test {

struct Gpu {
    std::shared_ptr<gpu::Device>        device;
    std::unique_ptr<gpu::ShaderLibrary> library;
};

/// The process's test device, or null (the test SKIPs).
inline Gpu* gpuOrNull() {
    static std::unique_ptr<Gpu> kGpu = [] () -> std::unique_ptr<Gpu> {
        auto device = gpu::Device::create();
        if (!device) {
            return nullptr;
        }
        auto made = std::make_unique<Gpu>();
        made->device = *device;
        made->library = std::make_unique<gpu::ShaderLibrary>(made->device);
        return made;
    }();
    return kGpu.get();
}

#define LRT_REQUIRE_GPU(name)                         \
    ::lrt::test::Gpu* name = ::lrt::test::gpuOrNull(); \
    if (name == nullptr) {                             \
        SKIP("no GPU device");                         \
    }

/// A buffer of `count` zeroed words: a counter a kernel adds to, a worst
/// case it maxes. Zeroed on purpose -- a buffer nobody wrote is not a
/// buffer of zeros on CUDA, and a counter that starts from what the device
/// last left there reads as garbage (the light BVH's draws did, on the L4).
inline gpu::Buffer uintBuffer(gpu::Device& device, uint64_t count, const char* label) {
    gpu::BufferDesc desc;
    desc.bytes = std::max<uint64_t>(count, 1) * sizeof(uint32_t);
    desc.elementBytes = sizeof(uint32_t);
    desc.label = label;
    const std::vector<uint32_t> zeros(std::max<uint64_t>(count, 1), 0u);
    auto made = gpu::Buffer::create(device, desc, zeros.data());
    REQUIRE(made);
    return *made;
}

/// The kernel in `module` whose entry point is named after the module, in
/// camelCase ("lrt/test/sort_stats" -> "sortStats"). `main` is not usable: Metal
/// reserves it.
inline std::string entryFor(const std::string& module) {
    std::string base = module.substr(module.rfind('/') + 1);
    std::string out;
    bool upper = false;
    for (char ch : base) {
        if (ch == '_') {
            upper = true;
            continue;
        }
        out += upper ? static_cast<char>(std::toupper(static_cast<unsigned char>(ch))) : ch;
        upper = false;
    }
    return out;
}

inline gpu::ComputeKernel kernel(Gpu& gpu, const std::string& module) {
    auto made = gpu::ComputeKernel::create(*gpu.library, module, entryFor(module));
    if (!made) {
        FAIL(made.error().toString());
    }
    return std::move(*made);
}

/// Folds 8-wide stats rows on the GPU and reads back the single row.
inline std::array<uint32_t, 8> reduceStats(Gpu& gpu, const gpu::Buffer& stats, uint32_t rows) {
    static gpu::ComputeKernel kReduce = kernel(gpu, "lrt/test/stats_reduce");
    gpu::Buffer result = uintBuffer(*gpu.device, 8, "stats.result");
    gpu::CommandBatch batch(*gpu.device);
    kReduce.dispatch(batch, {1, 1, 1}, [&](rhi::ShaderCursor cursor) {
        cursor["stats"].setBinding(stats.rhi());
        cursor["result"].setBinding(result.rhi());
        cursor["params"]["chunkCount"].setData(rows);
    });
    REQUIRE(batch.submit(true));
    std::array<uint32_t, 8> row{};
    REQUIRE(result.read(*gpu.device, 0, sizeof(row), row.data()));
    return row;
}

/// A frame written for a human to look at, when LRT_TEST_DUMP names a
/// directory: linear RGBA floats to an 8-bit PPM, clamped and gamma 2.2. A
/// debug dump, not an oracle -- nothing here is asserted on, and it is the one
/// place a test turns floats into bytes on the host.
inline void dumpPpm(const std::string& name, const float* rgba, uint32_t width, uint32_t height) {
    const char* dir = std::getenv("LRT_TEST_DUMP");
    if (dir == nullptr || *dir == '\0') {
        return;
    }
    const std::string path = std::string(dir) + "/" + name + ".ppm";
    FILE* out = std::fopen(path.c_str(), "wb");
    if (out == nullptr) {
        return;
    }
    std::fprintf(out, "P6\n%u %u\n255\n", width, height);
    std::vector<unsigned char> row(size_t{width} * 3);
    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
            const float* px = rgba + (size_t{y} * width + x) * 4;
            for (int c = 0; c < 3; ++c) {
                const float v = std::min(std::max(px[c], 0.0F), 1.0F);
                row[size_t{x} * 3 + static_cast<size_t>(c)] =
                    static_cast<unsigned char>(std::lround(std::pow(v, 1.0F / 2.2F) * 255.0F));
            }
        }
        std::fwrite(row.data(), 1, row.size(), out);
    }
    std::fclose(out);
    std::printf("  [dump] %s\n", path.c_str());
}

/// The same from a device buffer of float4 pixels.
inline void dumpPpm(Gpu& gpu, const std::string& name, const gpu::Buffer& colour, uint32_t width, uint32_t height) {
    const char* dir = std::getenv("LRT_TEST_DUMP");
    if (dir == nullptr || *dir == '\0') {
        return;
    }
    std::vector<float> rgba(size_t{width} * height * 4);
    if (!colour.read(*gpu.device, 0, rgba.size() * sizeof(float), rgba.data())) {
        return;
    }
    dumpPpm(name, rgba.data(), width, height);
}

}   // namespace lrt::test
